USE [sqldb-glass-dev-rc]
GO

/****** Object:  Table [dbo].[RC_COSTS_EXTRACT]    Script Date: 7/04/2025 11:07:47 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RC_COSTS_EXTRACT]') AND type in (N'U'))
DROP TABLE [dbo].[RC_COSTS_EXTRACT]
GO

/****** Object:  Table [dbo].[RC_COSTS_EXTRACT]    Script Date: 7/04/2025 11:07:47 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RC_COSTS_EXTRACT](
	[Debtor_Code] [int] NULL,
	[Client_Code] [nvarchar](500) NULL,
	[Client_Group] [nvarchar](500) NULL,
	[Chg_DEB] [decimal](18, 2) NULL,
	[Paid_DEB] [decimal](18, 2) NULL,
	[Chg_REF] [decimal](18, 2) NULL,
	[Paid_REF] [decimal](18, 2) NULL,
	[Chg_ADM] [decimal](18, 2) NULL,
	[Paid_ADM] [decimal](18, 2) NULL,
	[Chg_IBS] [decimal](18, 2) NULL,
	[Paid_IBS] [decimal](18, 2) NULL,
	[Chg_IBJ] [decimal](18, 2) NULL,
	[Paid_IBJ] [decimal](18, 2) NULL,
	[Chg_IAJ] [decimal](18, 2) NULL,
	[Paid_IAJ] [decimal](18, 2) NULL,
	[Chg_LET] [decimal](18, 2) NULL,
	[Paid_LET] [decimal](18, 2) NULL,
	[Chg_POR] [decimal](18, 2) NULL,
	[Paid_POR] [decimal](18, 2) NULL,
	[Chg_MPL] [decimal](18, 2) NULL,
	[Paid_MPL] [decimal](18, 2) NULL,
	[Chg_BNK] [decimal](18, 2) NULL,
	[Paid_BNK] [decimal](18, 2) NULL,
	[Chg_SHR] [decimal](18, 2) NULL,
	[Paid_SHR] [decimal](18, 2) NULL,
	[Chg_SHN] [decimal](18, 2) NULL,
	[Paid_SHN] [decimal](18, 2) NULL,
	[Chg_LOC] [decimal](18, 2) NULL,
	[Paid_LOC] [decimal](18, 2) NULL,
	[Chg_FCA] [decimal](18, 2) NULL,
	[Paid_FCA] [decimal](18, 2) NULL,
	[Chg_REP] [decimal](18, 2) NULL,
	[Paid_REP] [decimal](18, 2) NULL,
	[Chg_SEC] [decimal](18, 2) NULL,
	[Paid_SEC] [decimal](18, 2) NULL,
	[Chg_COU] [decimal](18, 2) NULL,
	[Paid_COU] [decimal](18, 2) NULL,
	[Chg_PRE] [decimal](18, 2) NULL,
	[Paid_PRE] [decimal](18, 2) NULL,
	[Chg_SSC] [decimal](18, 2) NULL,
	[Paid_SSC] [decimal](18, 2) NULL,
	[Chg_ESC] [decimal](18, 2) NULL,
	[Paid_ESC] [decimal](18, 2) NULL,
	[Chg_BAR] [decimal](18, 2) NULL,
	[Paid_BAR] [decimal](18, 2) NULL,
	[Chg_CRT] [decimal](18, 2) NULL,
	[Paid_CRT] [decimal](18, 2) NULL,
	[Chg_SRV] [decimal](18, 2) NULL,
	[Paid_SRV] [decimal](18, 2) NULL,
	[Chg_ATS] [decimal](18, 2) NULL,
	[Paid_ATS] [decimal](18, 2) NULL,
	[Chg_ADS] [decimal](18, 2) NULL,
	[Paid_ADS] [decimal](18, 2) NULL,
	[Chg_KIL] [decimal](18, 2) NULL,
	[Paid_KIL] [decimal](18, 2) NULL,
	[Chg_CMO] [decimal](18, 2) NULL,
	[Paid_CMO] [decimal](18, 2) NULL,
	[Chg_HEA] [decimal](18, 2) NULL,
	[Paid_HEA] [decimal](18, 2) NULL,
	[Chg_AFF] [decimal](18, 2) NULL,
	[Paid_AFF] [decimal](18, 2) NULL,
	[Chg_OTH] [decimal](18, 2) NULL,
	[Paid_OTH] [decimal](18, 2) NULL,
	[Chg_COJ] [decimal](18, 2) NULL,
	[Paid_COJ] [decimal](18, 2) NULL,
	[Chg_ADR] [decimal](18, 2) NULL,
	[Paid_ADR] [decimal](18, 2) NULL,
	[Chg_ADN] [decimal](18, 2) NULL,
	[Paid_ADN] [decimal](18, 2) NULL,
	[Chg_BAI] [decimal](18, 2) NULL,
	[Paid_BAI] [decimal](18, 2) NULL,
	[Chg_REG] [decimal](18, 2) NULL,
	[Paid_REG] [decimal](18, 2) NULL,
	[Chg_DEBR] [decimal](18, 2) NULL,
	[Paid_DEBR] [decimal](18, 2) NULL,
	[Chg_DEBW] [decimal](18, 2) NULL,
	[Paid_DEBW] [decimal](18, 2) NULL,
	[Chg_SERV] [decimal](18, 2) NULL,
	[Paid_SERV] [decimal](18, 2) NULL,
	[Chg_SUND] [decimal](18, 2) NULL,
	[Paid_SUND] [decimal](18, 2) NULL,
	[Chg_UIL] [decimal](18, 2) NULL,
	[Paid_UIL] [decimal](18, 2) NULL,
	[Chg_SCN] [decimal](18, 2) NULL,
	[Paid_SCN] [decimal](18, 2) NULL,
	[Chg_VLC] [decimal](18, 2) NULL,
	[Paid_VLC] [decimal](18, 2) NULL,
	[Chg_ILD] [decimal](18, 2) NULL,
	[Paid_ILD] [decimal](18, 2) NULL,
	[Chg_VLD] [decimal](18, 2) NULL,
	[Paid_VLD] [decimal](18, 2) NULL,
	[Chg_ILC] [decimal](18, 2) NULL,
	[Paid_ILC] [decimal](18, 2) NULL,
	[Chg_PHC] [decimal](18, 2) NULL,
	[Paid_PHC] [decimal](18, 2) NULL,
	[Chg_AHF] [decimal](18, 2) NULL,
	[Paid_AHF] [decimal](18, 2) NULL,
	[Chg_ICS] [decimal](18, 2) NULL,
	[Paid_ICS] [decimal](18, 2) NULL,
	[Chg_LIST] [decimal](18, 2) NULL,
	[Paid_LIST] [decimal](18, 2) NULL,
	[Chg_SHRF] [decimal](18, 2) NULL,
	[Paid_SHRF] [decimal](18, 2) NULL,
	[Chg_SHRC] [decimal](18, 2) NULL,
	[Paid_SHRC] [decimal](18, 2) NULL,
	[Chg_SRVI] [decimal](18, 2) NULL,
	[Paid_SRVI] [decimal](18, 2) NULL,
	[Chg_SRVC] [decimal](18, 2) NULL,
	[Paid_SRVC] [decimal](18, 2) NULL,
	[Chg_CLC] [decimal](18, 2) NULL,
	[Paid_CLC] [decimal](18, 2) NULL,
	[Chg_STB] [decimal](18, 2) NULL,
	[Paid_STB] [decimal](18, 2) NULL,
	[Chg_SEB] [decimal](18, 2) NULL,
	[Paid_SEB] [decimal](18, 2) NULL,
	[Chg_AUD] [decimal](18, 2) NULL,
	[Paid_AUD] [decimal](18, 2) NULL,
	[Chg_SCOS] [decimal](18, 2) NULL,
	[Paid_SCOS] [decimal](18, 2) NULL,
	[Chg_ARC] [decimal](18, 2) NULL,
	[Paid_ARC] [decimal](18, 2) NULL,
	[Chg_ICL] [decimal](18, 2) NULL,
	[Paid_ICL] [decimal](18, 2) NULL,
	[Chg_SAP] [decimal](18, 2) NULL,
	[Paid_SAP] [decimal](18, 2) NULL,
	[Chg_ACOM] [decimal](18, 2) NULL,
	[Paid_ACOM] [decimal](18, 2) NULL,
	[Chg_COL] [decimal](18, 2) NULL,
	[Paid_COL] [decimal](18, 2) NULL,
	[Chg_INT] [decimal](18, 2) NULL,
	[Paid_INT] [decimal](18, 2) NULL,
	[Chg_BCOM] [decimal](18, 2) NULL,
	[Paid_BCOM] [decimal](18, 2) NULL,
	[Chg_PMA] [decimal](18, 2) NULL,
	[Paid_PMA] [decimal](18, 2) NULL,
	[Chg_LATE] [decimal](18, 2) NULL,
	[Paid_LATE] [decimal](18, 2) NULL,
	[Chg_AKF] [decimal](18, 2) NULL,
	[Paid_AKF] [decimal](18, 2) NULL,
	[Chg_EST] [decimal](18, 2) NULL,
	[Paid_EST] [decimal](18, 2) NULL,
	[Chg_BRE][decimal](18, 2) NULL,
	[Paid_BRE] [decimal](18, 2) NULL,
	[Chg_DAR][decimal](18, 2) NULL,
	[Paid_DAR] [decimal](18, 2) NULL
) ON [PRIMARY]
GO


