USE [sqldb-glass-dev-rc]
GO

/****** Object:  Table [dbo].[RC_DEBTOR]    Script Date: 9/04/2025 8:27:19 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RC_DEBTOR]') AND type in (N'U'))
DROP TABLE [dbo].[RC_DEBTOR]
GO

/****** Object:  Table [dbo].[RC_DEBTOR]    Script Date: 9/04/2025 8:27:19 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RC_DEBTOR](
	[Debt_Code] [int] NULL,
	[Client_Code] [nvarchar](100) NULL,
	[Client_Group_Code] [nvarchar](100) NULL,
	[Account_No] [nvarchar](100) NULL,
	[Debtor_Code] [nvarchar](1000) NULL,
	[Company_Surname] [nvarchar](1000) NULL,
	[First_Name] [nvarchar](1000) NULL,
	[Street_Address] [nvarchar](1000) NULL,
	[Leg_Type] [nvarchar](1000) NULL,
	[Salutation] [nvarchar](1000) NULL,
	[Mailing_Address] [nvarchar](1000) NULL,
	[Legal_Address] [nvarchar](1000) NULL,
	[Date_Time_Entered] [datetime] NULL,
	[Fax_No] [nvarchar](1000) NULL,
	[Drivers_Licence] [nvarchar](1000) NULL,
	[Car_Reg_No] [nvarchar](1000) NULL,
	[Contact] [nvarchar](1000) NULL,
	[Title] [nvarchar](1000) NULL,
	[Trading_Name] [nvarchar](1000) NULL,
	[Aliases] [nvarchar](1000) NULL,
	[Sex] [nvarchar](1000) NULL,
	[Email_Addr] [nvarchar](1000) NULL,
	[A_C_N] [nvarchar](1000) NULL,
	[Birth_Date] [datetime] NULL,
	[Employer_Name] [nvarchar](1000) NULL,
	[Employers_Address] [nvarchar](1000) NULL,
	[Employers_Phone_H] [nvarchar](1000) NULL,
	[Employers_Phone_H_1] [nvarchar](1000) NULL,
	[Employers_Phone_H_2] [nvarchar](1000) NULL,
	[Employers_Contact] [nvarchar](1000) NULL,
	[A_B_N] [nvarchar](1000) NULL,
	[External_Contact_March_Flag] [nvarchar](1000) NULL,
	[External_Match_Request_Sent] [datetime] NULL,
	[External_Match_Received_Date] [nvarchar](1000) NULL,
	[Company_Name_Searched] [nvarchar](1000) NULL,
	[Acn_Number_Searched] [nvarchar](1000) NULL,
	[ABN_Number_Searched] [nvarchar](1000) NULL,
	[Date_Registered] [nvarchar](1000) NULL,
	[Director_Name] [nvarchar](1000) NULL,
	[Director_Dob] [nvarchar](1000) NULL,
	[Director_Name_1] [nvarchar](1000) NULL,
	[Director_Dob_1] [nvarchar](1000) NULL,
	[Operator_Entering_Search] [nvarchar](1000) NULL,
	[Search_Date_Entered] [nvarchar](1000) NULL,
	[Company_Search_Time] [nvarchar](1000) NULL,
	[Sol_Code] [nvarchar](1000) NULL,
	[Solicitors_Reference] [nvarchar](1000) NULL,
	[Representative_Name] [nvarchar](1000) NULL,
	[Rep_Other_Info] [nvarchar](1000) NULL,
	[Rep_Home_Ph] [nvarchar](1000) NULL,
	[Search_Look_Up_String] [nvarchar](1000) NULL,
	[Contact_Rep_First] [nvarchar](1000) NULL,
	[Customer_Reference] [nvarchar](1000) NULL,
	[Debtor_Relationship] [nvarchar](1000) NULL,
	[Police_Report] [nvarchar](1000) NULL,
	[Debt_Relationship] [nvarchar](1000) NULL,
	[Driver_Licence_State] [nvarchar](1000) NULL,
	[Phone_C] [nvarchar](1000) NULL,
	[Rep_Start_Dte] [nvarchar](1000) NULL,
	[Rep_End_Dte] [nvarchar](1000) NULL,
	[Mail_Rep_First] [nvarchar](1000) NULL,
	[Block_Letter] [nvarchar](1000) NULL,
	[Representative_Block_Letter] [nvarchar](1000) NULL,
	[Address] [nvarchar](1000) NULL,
	[column64] [nvarchar](1000) NULL,
	[Person_Id] [nvarchar](1000) NULL,
	[Person_Type] [nvarchar](1000) NULL,
	[Nationality] [nvarchar](1000) NULL,
	[Id_Type] [nvarchar](1000) NULL,
	[Id_Detail] [nvarchar](1000) NULL,
	[Special_Needs] [nvarchar](1000) NULL,
	[Privacy_Act_Read] [nvarchar](1000) NULL,
	[AddrVal_Skip_By] [nvarchar](1000) NULL,
	[AddrVal_Skip_Dte] [nvarchar](1000) NULL,
	[AddrVal_Skip_Level] [nvarchar](1000) NULL,
	[Date_Last_Sequenced] [nvarchar](1000) NULL,
	[Email] [nvarchar](1000) NULL,
	[Police_Station] [nvarchar](1000) NULL,
	[Police_Station_Phone_No] [nvarchar](1000) NULL,
	[Police_Station_Contact_Officer] [nvarchar](1000) NULL,
	[Representative_Date_Of_Birth] [nvarchar](1000) NULL,
	[People_Key] [nvarchar](1000) NULL,
	[Debtor_Other_Phone_Numbers] [nvarchar](max) NULL,
	[Debtor_Other_Email_Addresses] [nvarchar](max) NULL,
	[Bankruptcy] [nvarchar](1000) NULL,
	[Bankruptcy_Number] [nvarchar](1000) NULL,
	[Bank_Branch] [nvarchar](1000) NULL,
	[Phone_Number] [nvarchar](max) NULL,
	[Ph_Type] [nvarchar](max) NULL,
	[Ph_Valid] [nvarchar](max) NULL,
	[Phone_Start] [nvarchar](max) NULL,
	[Phone_End] [nvarchar](max) NULL,
	[Phone_Seq] [nvarchar](max) NULL,
	[Phone_Last_Contact_Date_Time] [nvarchar](max) NULL,
	[Phone_Score] [nvarchar](max) NULL,
	[Rep] [nvarchar](2000) NULL,
	[Phone_Preferred_Flag] [nvarchar](2000) NULL,
	[Ph_Change_Date_Time] [nvarchar](max) NULL,
	[Ph_Changed_By] [nvarchar](max) NULL,
	[Phone_Source] [nvarchar](max) NULL,
	[Scorecolourload] [nvarchar](1000) NULL,
	[Debtageload] [nvarchar](1000) NULL,
	[Deceased_Flag] [nvarchar](1000) NULL,
	[Date_Last_Used] [nvarchar](1000) NULL,
	[Preferred_Channel] [nvarchar](1000) NULL,
	[Date_Last_Used_1] [nvarchar](1000) NULL,
	[First_Time] [nvarchar](1000) NULL,
	[Second_Time] [nvarchar](1000) NULL,
	[Third_Time] [nvarchar](1000) NULL,
	[Fourth_Time] [nvarchar](1000) NULL,
	[Fifth_Time] [nvarchar](1000) NULL,
	[Passport_Number] [nvarchar](1000) NULL,
	[Dw_Provider] [nvarchar](max) NULL,
	[Dw_Last_Sent] [nvarchar](max) NULL,
	[Dw_Last_Return_Provider] [nvarchar](max) NULL,
	[Dw_Last_Return_Date] [nvarchar](max) NULL,
	[Company_Industry] [nvarchar](1000) NULL,
	[Field_Call_Addresses] [nvarchar](1000) NULL,
	[Police_Email] [nvarchar](1000) NULL,
	[Preferred_Contact_Method] [nvarchar](1000) NULL,
	[Block_SMS] [nvarchar](1000) NULL,
	[Block_Email] [nvarchar](1000) NULL,
	[Representative_Block_SMS] [nvarchar](1000) NULL,
	[Representative_Block_Email] [nvarchar](1000) NULL,
	[Sent_To_Dialler] [datetime] NULL,
	[Preferred_Language] [nvarchar](1000) NULL,
	[Workcover] [nvarchar](1000) NULL,
	[Insurance_Company] [nvarchar](1000) NULL,
	[Insurance_Claim_Number] [nvarchar](1000) NULL,
	[Relation_1] [nvarchar](1000) NULL,
	[Relation_2] [nvarchar](1000) NULL,
	[Relation_3] [nvarchar](1000) NULL,
	[Bankruptcy_Date] [nvarchar](1000) NULL,
	[Bankruptcy_Administrator] [nvarchar](1000) NULL,
	[Email_Consent_Fields] [nvarchar](1000) NULL,
	[Last_Recent_Portal_Visit_Reminder_Type] [nvarchar](1000) NULL,
	[Allow_Ccb] [nvarchar](1000) NULL,
	[Other_Police_Report] [nvarchar](1000) NULL,
	[Other_Police_Stations] [nvarchar](1000) NULL,
	[Vulnerability_Date] [nvarchar](1000) NULL,
	[Vulnerability_Description] [nvarchar](1000) NULL,
	[Vulnerability_Identified_By] [nvarchar](1000) NULL,
	[Vulnerability_Comments] [nvarchar](1000) NULL,
	[Person_Id_1] [nvarchar](1000) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


