USE [sqldb-glass-dev-rc]
GO

/****** Object:  Table [dbo].[RC_DRDEBTORAUD]    Script Date: 9/04/2025 8:29:22 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RC_DRDEBTORAUD]') AND type in (N'U'))
DROP TABLE [dbo].[RC_DRDEBTORAUD]
GO

/****** Object:  Table [dbo].[RC_DRDEBTORAUD]    Script Date: 9/04/2025 8:29:22 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RC_DRDEBTORAUD](
	[Extended_Debt_Code] [int] NULL,
	[Client_Code] [nvarchar](500) NULL,
	[Client_Group_Code] [nvarchar](500) NULL,
	[Account_No] [nvarchar](100) NULL,
	[Debtor_Code] [nvarchar](100) NULL,
	[Date_Time_Changed] [datetime] NULL,
	[Street_Address_Line1] [nvarchar](500) NULL,
	[Street_Number] [nvarchar](500) NULL,
	[Street_Name] [nvarchar](100) NULL,
	[Street_Suburb] [nvarchar](500) NULL,
	[Street_State] [nvarchar](500) NULL,
	[Street_Post_Code] [nvarchar](100) NULL,
	[Street_Country] [nvarchar](100) NULL,
	[Street_Start_Date] [datetime] NULL,
	[Street_End_Date] [datetime] NULL,
	[Mailing_Address] [nvarchar](500) NULL,
	[Mailing_Address_Number] [nvarchar](500) NULL,
	[Mailing_Address_Name] [nvarchar](100) NULL,
	[Mailing_Suburb] [nvarchar](500) NULL,
	[Mailing_State] [nvarchar](500) NULL,
	[Mailing_Post_Code] [nvarchar](100) NULL,
	[Mailing_Country] [nvarchar](100) NULL,
	[Mailing_Start_Date] [datetime] NULL,
	[Mailing_End_Date] [datetime] NULL,
	[Company_Surname] [nvarchar](500) NULL,
	[Operator] [nvarchar](500) NULL,
	[Phone_M] [nvarchar](100) NULL,
	[Mobile_Phone_Start] [datetime] NULL,
	[Mobile_Phone_End] [datetime] NULL,
	[Phone_W] [nvarchar](500) NULL,
	[Work_Phone_Start] [datetime] NULL,
	[Work_Phone_End] [datetime] NULL,
	[Fax_No] [nvarchar](100) NULL,
	[Fax_Phone_Start] [datetime] NULL,
	[Fax_Phone_End] [datetime] NULL,
	[First_Name] [nvarchar](50) NULL,
	[Legal_Address_Line1] [nvarchar](500) NULL,
	[Legal_Address_Line2] [nvarchar](500) NULL,
	[Legal_Suburb] [nvarchar](500) NULL,
	[Legal_State] [nvarchar](500) NULL,
	[Legal_Post_Code] [nvarchar](500) NULL,
	[Legal_Country] [nvarchar](500) NULL,
	[Update_Source] [nvarchar](500) NULL,
	[Business_Address_Line1] [nvarchar](500) NULL,
	[Business_Address_Line2] [nvarchar](500) NULL,
	[Business_Address_Line3] [nvarchar](500) NULL,
	[Business_Suburb] [nvarchar](500) NULL,
	[Business_State] [nvarchar](500) NULL,
	[Business_Post_Code] [nvarchar](500) NULL,
	[Business_Country] [nvarchar](500) NULL,
	[Individual_Street_Default] [nvarchar](100) NULL,
	[Individual_Mail_Default] [nvarchar](100) NULL,
	[Default] [nvarchar](100) NULL,
	[Business_Mail_Default] [nvarchar](100) NULL,
	[Salutation] [nvarchar](100) NULL,
	[Title] [nvarchar](100) NULL,
	[Sex] [nvarchar](100) NULL,
	[Date_Of_Birth] [datetime] NULL,
	[Email_Address] [nvarchar](500) NULL,
	[Representative_Name] [nvarchar](500) NULL,
	[Representative_Relationship] [nvarchar](100) NULL,
	[Rep_Std] [nvarchar](100) NULL,
	[Rep_Phone] [nvarchar](100) NULL,
	[Temporary_Address_1] [nvarchar](100) NULL,
	[Temporary_Address_2] [nvarchar](100) NULL,
	[Temporary_Address_3] [nvarchar](100) NULL,
	[Temporary_Suburb] [nvarchar](100) NULL,
	[Temporary_State] [nvarchar](100) NULL,
	[Temporary_Post_Code] [nvarchar](100) NULL,
	[Temporary_Country] [nvarchar](100) NULL,
	[Temporary_Start_Date] [datetime] NULL,
	[Temporary_End_Date] [datetime] NULL,
	[Temporary_Default] [nvarchar](100) NULL,
	[Term_Address_1] [nvarchar](100) NULL,
	[Term_Address_2] [nvarchar](100) NULL,
	[Term_Address_3] [nvarchar](100) NULL,
	[Term_Suburb] [nvarchar](100) NULL,
	[Term_State] [nvarchar](100) NULL,
	[Term_Post_Code] [nvarchar](100) NULL,
	[Term_Country] [nvarchar](100) NULL,
	[Term_Start_Date] [datetime] NULL,
	[Term_End_Date] [datetime] NULL,
	[Term_Default] [nvarchar](100) NULL,
	[Contact_Phone_STD] [nvarchar](100) NULL,
	[Contact_Phone_C] [nvarchar](100) NULL,
	[Contact_Phone_Start] [datetime] NULL,
	[Contact_Phone_End] [datetime] NULL,
	[Trading_Name] [nvarchar](100) NULL,
	[Abn] [nvarchar](100) NULL,
	[Business_Name] [nvarchar](100) NULL,
	[Employer_Name] [nvarchar](100) NULL,
	[Employer_Address_Line_1] [nvarchar](500) NULL,
	[Employer_Address_Line2] [nvarchar](500) NULL,
	[Employer_Address_Line3] [nvarchar](500) NULL,
	[Employer_Suburb] [nvarchar](500) NULL,
	[Employer_State] [nvarchar](500) NULL,
	[Employer_Post_Code] [nvarchar](500) NULL,
	[Employer_Work_Phone] [nvarchar](500) NULL,
	[Phone_E] [nvarchar](500) NULL,
	[Employee_Mobile] [nvarchar](500) NULL,
	[Sent_To_Clink] [datetime] NULL,
	[Contact_Rep] [int] NULL,
	[Mail_Rep] [nvarchar](100) NULL,
	[Rep_Start_Dte] [nvarchar](1000) NULL,
	[Rep_End_Dte] [nvarchar](100) NULL,
	[Rep_Addr1] [nvarchar](500) NULL,
	[Rep_Addr2] [nvarchar](1000) NULL,
	[Rep_Addr3] [nvarchar](1000) NULL,
	[Rep_Suburb] [nvarchar](1000) NULL,
	[Rep_State] [nvarchar](1000) NULL,
	[rep_post_code] [nvarchar](1000) NULL,
	[Block_Letter] [nvarchar](500) NULL,
	[Licence] [nvarchar](1000) NULL,
	[Other_Phone_Number] [nvarchar](500) NULL,
	[Other_Email_Address] [nvarchar](1000) NULL,
	[Bankruptcy] [nvarchar](1000) NULL,
	[Bankruptcy_Number] [nvarchar](1000) NULL,
	[Contact] [nvarchar](500) NULL,
	[Bank_Name] [nvarchar](1000) NULL,
	[Bank_Branch] [nvarchar](1000) NULL,
	[Phone_No] [nvarchar](max) NULL,
	[Type] [nvarchar](2000) NULL,
	[Validity] [nvarchar](2000) NULL,
	[Phone_Start] [datetime] NULL,
	[Phone_End] [datetime] NULL,
	[Phone_Seq] [nvarchar](500) NULL,
	[Phone_Last_Contact_Date_Time] [datetime] NULL,
	[Phone_Score] [nvarchar](2000) NULL,
	[Rep] [nvarchar](2000) NULL,
	[Phone_No_Changed_By] [nvarchar](2000) NULL,
	[Phone_No_Changed_Date_Time] [nvarchar](2000) NULL,
	[Call_Preference_Type] [nvarchar](1000) NULL,
	[Call_Date_Last_Used] [datetime] NULL,
	[Corr_Pref_Type] [nvarchar](100) NULL,
	[Corr_Date_Last_Used] [datetime] NULL,
	[Block_SMS] [nvarchar](100) NULL,
	[Block_Email] [nvarchar](100) NULL,
	[ZID] [nvarchar](100) NULL
) ON [PRIMARY]
GO


