INSERT  INTO tblDebtContact WITH ( ROWLOCK )
        ( [AccountID] ,
          [ContactID] ,
          [DebtContactsTS] ,
          [Type] ,
          [Phone] ,
          [Outcome] ,
          [LetterAddress] ,
          [DocumentRefNo] ,
          [DatePrinted] ,
          [PaymentCode] ,
          [DateSenttoClient] ,
          [SmsOutcome] ,
          [PoiKey] ,
          [LetterName] ,
          [DateDequeued] ,
          [DateReturned] ,
          [MultiRecipientKey] ,
          [LetterTotalOutstanding] ,
          [SMSKey] ,
          [RequestCallDeletionDate] ,
          [RequestCallDeletionOperator] ,
          [EmailAddress] ,
          --[Solicited] ,
          [SenttoClient] ,
          [WorkdeskEmailKey] ,
          [AkEmailKey] ,
          [ActivityReportSent] ,
          [CreateID] ,
          [CreateSessionID] ,
          [CreateTS] ,
          [StatusID]
        )
        SELECT  A.AccountID ,
                C.ContactID ,
                DC.[Date] ,
                DC.[Type] ,
                DC.[Phone] ,
                DC.[Outcome] ,
                DC.[Letter_Address] ,
                DC.[Document_Ref_No] ,
                DC.[Date_Printed] ,
                DC.[Payment_Code] ,
                DC.[Date_Sent_to_Client] ,
                DC.[Sms_Outcome] ,
                DC.[Poi_Key] ,
                DC.[Letter_Name] ,
                DC.[Date_De_queued] ,
                DC.[Date_Returned] ,
                DC.[Multi_Recipient_Key] ,
                DC.[Letter_Total_Outstanding] ,
                DC.[SMS_Key] [int] ,
                DC.[Request_Call_Deletion_Date] ,
                DC.[Request_Call_Deletion_Operator] ,
                DC.[Email_Address] ,
                --DC.[Solicited] ,
                DC.[Sent_to_Client] ,
                DC.[Workdesk_Email_Key] ,
                DC.[Ak_Email_Key] ,
                DC.[Activity_Report_Sent] ,
                1 ,
                {{CurrentSessionID}} ,
                GETDATE() ,
                1
        FROM    RC_DEBT_CONTACTS DC
                INNER JOIN tblAccount A WITH ( NOLOCK ) ON A.AccountNumberPrevious = DC.Extended_Debt_Code
                LEFT JOIN tblContact C WITH ( NOLOCK ) ON C.Z_REF2 = DC.Multi_Recipient_Key
        WHERE   A.LoadID = {{LoadID}}
        ;