USE [sqldb-glass-dev-rc]
GO
-- 27/08/26 CC Change to add addional fields for tranche #1
--

/****** Object:  Table [dbo].[RC_DRDEBTINFO]    Script Date: 27/08/2025 11:09:03 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RC_DRDEBTINFO]') AND type in (N'U'))
DROP TABLE [dbo].[RC_DRDEBTINFO]
GO

/****** Object:  Table [dbo].[RC_DRDEBTINFO]    Script Date: 27/08/2025 11:09:03 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[RC_DRDEBTINFO](
	[Full_Debt_Code] [int] NULL,
	[Client_Code] [nvarchar](10) NULL,
	[Client_Group] [nvarchar](50) NULL,
	[Short_Debt_Code] [int] NULL,
	[Account_No] [nvarchar](100) NULL,
	[Mothers_Maiden_Name] [nvarchar](100) NULL,
	[Blank3] [nvarchar](200) NULL,
	[Comments] [nvarchar](max) NULL,
	[Indemnity_Debt_Amt_Of_Settlement] [decimal](18, 2) NULL,
	[Settlement_Balance_Due_Date_Execution_Address_1] [nvarchar](max) NULL,
	[Employer_s_Name_Execution_Postcode] [nvarchar](max) NULL,
	[Last_Hardship_Date] [datetime] NULL,
	[Last_Pay_Date_Before_Referral] [datetime] NULL,
	[Last_Pay_Amt_Before_Referral] [decimal](18, 2) NULL,
	[Date_Of_Last_Letter_Sent] [datetime] NULL,
	[Direct_Debit_Date] [nvarchar](1000) NULL,
	[Summary_of_Issues_3_Current_Life_Support_Flag_T_Party_Issued_Against_Insured_Y_N] [nvarchar](max) NULL,
	[Total_Outstanding_Total_Debts_for_all_Creditors_Total_Amt_Confesssed] [decimal](18, 2) NULL,
	[Int_Amt_Stated_on_Acc_Int_Amt_Confessed] [decimal](18, 2) NULL,
	[Receipt_Address_1] [nvarchar](1000) NULL,
	[Receipt_Address_2] [nvarchar](1000) NULL,
	[Amount_Paid_Total_Payments] [nvarchar](1000) NULL,
	[Previous_Judgt_Date] [datetime] NULL,
	[Prev_Judgt_Costs] [decimal](18, 2) NULL,
	[Solicitor_Name] [nvarchar](1000) NULL,
	[Bill_Amounts_Document_Amount] [nvarchar](1000) NULL,
	[Bill_Cycle_Due_Day] [nvarchar](max) NULL,
	[Brand] [nvarchar](max) NULL,
	[Account_Type_Additional_Worktype] [nvarchar](1000) NULL,
	[Interest_Rate] [decimal](18, 2) NULL,
	[Client_Advice] [nvarchar](max) NULL,
	[Blank4] [nvarchar] (100) NULL,
	[Agent_Name] [nvarchar](max) NULL,
	[Agent_Address_1] [nvarchar](max) NULL,
	[Agent_Address_2] [nvarchar](max) NULL,
	[Agent_Suburb] [nvarchar](1000) NULL,
	[Agent_State] [nvarchar](1000) NULL,
	[Agent_Postcode] [nvarchar](1000) NULL,
	[Agent_Phone_No] [nvarchar](1000) NULL,
	[Last_Payment_Date] [datetime] NULL,
	[Last_Payment_Amount] [decimal](18, 2) NULL,
	[Overdue_Amount] [decimal](18, 2) NULL,
	[Tot_Amt_Due] [decimal](18, 2) NULL,
	[Application_Address_Event_Date_For_Ahri_Client_Registered_Proprietor_Address_1] [nvarchar](max) NULL,
	[Previous_Address_Previous_Details_Registered_Proprietor_Suburb] [nvarchar](max) NULL,
	[Lot_No] [nvarchar](max) NULL,
	[NAB_Original_Loan_Amount] [decimal](18, 2) NULL,
	[NAB_Payment_Status] [nvarchar](max) NULL,
	[Initial_Payment_Amount_NAB_Arrangement_Amount] [decimal](18, 2) NULL,
	[Broken_Arrangement_Date_Arrangement_Frequency_NAB_Arrangement_Frequency] [nvarchar](max) NULL,
	[NAB_Letter_Date] [datetime] NULL,
	[NAB_Instruction] [nvarchar](max) NULL,
	[Account_Status] [nvarchar](max) NULL,
	[Claim_No_PRN_Number] [nvarchar](max) NULL,
	[Centrelink_Region_Office_Code_Location_Code_Previous_Primary_Acc_No] [nvarchar](1000) NULL,
	[Centrelink_Recovery_Period_End_Date_Loan_Term_Original_Loan_Term] [nvarchar](1000) NULL,
	[Temporary_Credit_Limit] [decimal](18, 2) NULL,
	[Credit_Listing] [datetime] NULL,
	[Hardship_Request_Date] [datetime] NULL,
	[Hardhisp_Reason] [nvarchar](1000) NULL,
	[Hardship_Approval_Date] [datetime] NULL,
	[Hardhisp_Treatment_Type] [nvarchar](1000) NULL,
	[Hardship_Treatment_End_Date] [datetime] NULL,
	[Past_Due_Date] [datetime] NULL,
	[Account_Date_Last_Payment_Made] [datetime] NULL,
	[Account_Last_Payment_Amount] [decimal](18, 2) NULL,
	[Credit_Card_Minimum_Repayment] [decimal](18, 2) NULL,
	[Instalment_Value] [decimal](18, 2) NULL,
	[Due_Date] [datetime] NULL,
	[Loan_Amount] [decimal](18, 2) NULL,
	[Centrleink_Rang_Out_Client_Result_Nab_Crb_Acc_Id] [nvarchar](1000) NULL,
	[Centrleink_Rang_Out_Debtor_Result_Nab_Crb_Acc_Sub_Id] [nvarchar](1000) NULL,
	[Centrleink_Rang_Out_Representative_Result_Overdraft_Indicator] [nvarchar](1000) NULL,
	[Centrleink_E_W_P_Search_Success_y_n] [nvarchar](1000) NULL,
	[Third_Party_Driver_Request] [nvarchar](max) NULL,
	[Relatvie_Name] [nvarchar](1000) NULL,
	[Relative_s_Relationship_To_Debtor] [nvarchar](1000) NULL,
	[Relative_s_Telephone] [nvarchar](100) NULL,
	[Deceased_Date] [datetime] NULL,
	[Resident_Status] [nvarchar](1000) NULL,
	[Bill_Date_Payment_Date] [nvarchar](max) NULL,
	[Amount_Outstanding] [decimal](18,2) NULL,
	[Total_Charges_Tax_File_Number] [nvarchar](max) NULL,
	[Total_Amount_Due_A_B_N] [nvarchar](max) NULL,
	[Amount_Received_Cac] [nvarchar](max) NULL,
	[Bill_Adjustment_Debt_Type] [nvarchar](max) NULL,
	[Referred_Balance] [nvarchar](max) NULL,
	[Current_Balance] [nvarchar](max) NULL,
	[Warning_Date] [datetime] NULL,
	[Cred_Corp_Status] [nvarchar](max) NULL,
	[Cred_Corp_Entity] [nvarchar](max) NULL,
	[Cc_Payment_Amount] [decimal](18, 2) NULL,
	[Cred_Corp_Int_Date] [datetime] NULL,
	[Purchase_Price] [nvarchar](max) NULL,
	[Date_Account_Opened] [datetime] NULL,
	[Credit_Limit] [decimal](18, 2) NULL,
	[Charge_Off_Balance] [decimal](18, 2) NULL,
	[Autowithdraw] [nvarchar](max) NULL,
	[_3rd_Party_Auth] [int] NULL,
	[Return_Enrolment] [nvarchar](max) NULL,
	[Hardship_Flag_Self_Employed] [nvarchar](max) NULL,
	[Account_Class_Job_Class] [nvarchar](max) NULL,
	[Mercantile_Job_Title] [nvarchar](max) NULL,
	[Merc_Flag_Prev_Home_Area] [nvarchar](max) NULL,
	[Relationship_Postcode] [nvarchar](max) NULL,
	[Relationship_Phone_Area] [nvarchar](max) NULL,
	[Relationship_Phone_No] [nvarchar](max) NULL,
	[Accountant] [nvarchar](max) NULL,
	[Old_Post_Code] [nvarchar](max) NULL,
	[BPAY_reference] [nvarchar](max) NULL,
	[Last_Purchase_Date] [datetime] NULL,
	[Days_Delinquent] [nvarchar](max) NULL,
	[Arrears_Total_Overdue] [decimal](18, 2) NULL,
	[Last_Address_Change_Date] [datetime] NULL,
	[Account_Open_Date] [datetime] NULL,
	[Last_Bill_Date] [datetime] NULL,
	[Aged_History] [nvarchar](max) NULL,
	[Last_Monetary_Amount_Last_Pay_Amount] [decimal](18, 2) NULL,
	[Write_off_Date] [datetime] NULL,
	[Write_off_Amount] [decimal](18, 2) NULL,
	[Account_End_Date] [datetime] NULL,
	[Last_Monetary_Type_Last_Payment_Type] [nvarchar](1000) NULL,
	[Last_Monetary_Date_Last_Pay_Date] [date] NULL,
	[Business_Unit] [nvarchar](max) NULL,
	[Rent_Or_Own] [nvarchar](max) NULL,
	[Landlord_mort_Name_Times_In_Collection] [nvarchar](max) NULL,
	[Last_Activity_Date] [datetime] NULL,
	[Last_Contact_Activity] [nvarchar](max) NULL,
	[Current_Due] [decimal](18, 2) NULL,
	[Months_In_Arrears_Cycles_Delinquent] [nvarchar](max) NULL,
	[Default_List_Status] [nvarchar](max) NULL,
	[Concession_Concession_Type] [nvarchar](max) NULL,
	[Business_Name] [nvarchar](max) NULL,
	[Gross_Annual_Salary_Cancel_Reason] [nvarchar](200) NULL,
	[Card_Name] [nvarchar](1000) NULL,
	[Limit_on_application] [nvarchar](1000) NULL,
	[Cycle_Days] [nvarchar](1000) NULL,
	[Payment_Due_Amount] [decimal](18, 2) NULL,
	[Agency_Code] [nvarchar](max) NULL,
	[S88_Date_DN_Expiry_Date] [datetime] NULL,
	[Instal_Amount] [decimal](18, 2) NULL,
	[Next_Statement_Date] [datetime] NULL,
	[F412_Bal_Counter] [nvarchar](max) NULL,
	[Cba_Matter_Ref] [nvarchar](max) NULL,
	[Di_S88issdate] [datetime] NULL,
	[Days_Past_Due] [nvarchar](max) NULL,
	[Cycle_History_Date] [datetime] NULL,
	[Cycle_History_Days] [nvarchar](max) NULL,
	[Cycle_Days_History_Expected_Monthly_Minimum_Payment_Min_Pay_Updated] [nvarchar](max) NULL,
	[Cycle_Days_History_Total_Past_Due_Update] [nvarchar](max) NULL,
	[Minimum_Installment_Repay_Amount_Total_Exposure_Update] [nvarchar](max) NULL,
	[Amount_Outstanding_Update] [decimal] (18,2) NULL,
	[Date_Bals_Updated] [datetime] NULL,
	[Bill_No_Document_No_Billing_Code_Original_Creditor_Account_Ref] [nvarchar](max) NULL,
	[Bill_Reason] [nvarchar](max) NULL,
	[Bill_Total] [nvarchar](max) NULL,
	[Bill_Issued_Date] [nvarchar](1000) NULL,
	[Bill_Due_Date_Doc_Due_Date] [nvarchar](1000) NULL,
	[Total_Assets] [nvarchar](max) NULL,
	[Equip_Description] [nvarchar](max) NULL,
	[Asset_Description] [nvarchar](max) NULL,
	[Vin_Serial_Number] [nvarchar](max) NULL,
	[Registration_Number] [nvarchar](max) NULL,
	[Arrears_Past_Due_Upd] [nvarchar](50) NULL,
	[Arrears_30dy_Upd] [nvarchar](max) NULL,
	[Arrears_60dy_Upd] [nvarchar](max) NULL,
	[Arrears_90dy_Upd] [nvarchar](max) NULL,
	[Arrears_120dy_Upd] [nvarchar](max) NULL,
	[Arrears_150dy_Upd] [nvarchar](max) NULL,
	[Arrears_180dy_Upd] [nvarchar](max) NULL,
	[Arrears_Vintage_Upd] [nvarchar](max) NULL,
	[No_Time_Delinquent] [nvarchar](max) NULL,
	[No_Times_Bankrupt] [nvarchar](max) NULL,
	[Client_Name] [nvarchar](max) NULL,
	[Country_Of_Origin] [nvarchar](max) NULL,
	[Assignment_Id] [nvarchar](max) NULL,
	[Assignment_Type] [nvarchar](max) NULL,
	[Default_Date] [datetime] NULL,
	[Default_Amount] [decimal](18, 2) NULL,
	[Interest_To_Date] [decimal](18, 2) NULL,
	[Report_Status] [nvarchar](max) NULL,
	[Tdx_Closure_Reason_Code] [nvarchar](max) NULL,
	[Sent_To_Client] [nvarchar](max) NULL,
	[Di_Phones] [nvarchar](max) NULL,
	[Last_Letter_Date] [datetime] NULL,
	[Di_Applblkrc] [nvarchar](max) NULL,
	[Earliest_Transaction_Di_Entrydate] [nvarchar](max) NULL,
	[Last_Invoice_Id] [nvarchar](max) NULL,
	[Security_Details] [nvarchar](max) NULL,
	[Rent] [decimal](18, 2) NULL,
	[Maintenance] [decimal](18, 2) NULL,
	[Doc_Status_Billing_Method_Last_Pay_Method_Di_Tdxpaymeth] [nvarchar](max) NULL,
	[Di_Tdxprodno_Toll_Product] [nvarchar](max) NULL,
	[Di_Holddate] [datetime] NULL,
	[Di_Releasedate] [datetime] NULL,
	[Charge_Off_Date] [datetime] NULL,
	[Loan_Purpose] [nvarchar](max) NULL,
	[LoanDate] [datetime] NULL,
	[LoanRemaining_Term] [nvarchar](max) NULL,
	[Block_Re_class] [nvarchar](max) NULL,
	[Direct_Debit_Frequency] [nvarchar](max) NULL,
	[Direct_Debit_Amount] [decimal](18, 2) NULL,
	[Direct_Debit_Bsb] [nvarchar](max) NULL,
	[Direct_Debit_Account_No] [nvarchar](max) NULL,
	[Mortgage] [nvarchar](max) NULL,
	[Skiptrace_Status] [nvarchar](max) NULL,
	[Skiptrace_Keys] [nvarchar](max) NULL,
	[Account_Cycle_Date] [datetime] NULL,
	[Last_Database_Search] [nvarchar](max) NULL,
	[Status_Of_Search] [nvarchar](max) NULL,
	[Move_in_Date] [datetime] NULL,
	[Move_out_Date] [datetime] NULL,
	[NMI] [nvarchar](max) NULL,
	[Last_Due_Date] [datetime] NULL,
	[Last_Due_Amount] [decimal](18, 2) NULL,
	[End_Date] [datetime] NULL,
	[Company_Code] [nvarchar](max) NULL,
	[Determination_Id_CP_Account_No] [nvarchar](max) NULL,
	[Di_State] [nvarchar](max) NULL,
	[Death_Cert_Recd] [nvarchar](max) NULL,
	[Insurance_Ind] [nvarchar](max) NULL,
	[_6Q_Date] [nvarchar](max) NULL,
	[_21D_Date] [nvarchar](max) NULL,
	[_6Q_Amount] [decimal](18, 2) NULL,
	[_21D_Amount] [decimal](18, 2) NULL,
	[Exempt_Default] [nvarchar](max) NULL,
	[Skiptrace_Actioned] [nvarchar](max) NULL,
	[Review_Balance] [decimal](18, 2) NULL,
	[Balance_Adjustment_Type] [nvarchar](max) NULL,
	[Balance_Adjustment_Date] [nvarchar](1000) NULL,
	[Balance_Adjustment_Amount] [nvarchar](1000) NULL,
	[Over_Drawn_Letter_Date] [datetime] NULL,
	[Portal_Status] [nvarchar](max) NULL,
	[Thrid_Party_Bankrupt] [nvarchar](max) NULL,
	[Thrid_Party_Deceased] [nvarchar](max) NULL,
	[Comments_1] [nvarchar](max) NULL,
	[Last_Login_Date] [datetime] NULL,
	[Days_Since_Last_Login] [nvarchar](max) NULL,
	[Last_Login_Time] [nvarchar](max) NULL,
	[Login_Method] [nvarchar](max) NULL,
	[Less_Than_7_Days_Login] [nvarchar](max) NULL,
	[Less_Than_14_Days_Login] [nvarchar](max) NULL,
	[Less_Than_21_Days_Login] [nvarchar](max) NULL,
	[Di_More21dayslogin] [nvarchar](max) NULL,
	[Total_Logins] [nvarchar](max) NULL,
	[Total_Mobile_Logins] [nvarchar](max) NULL,
	[Total_Pc_Logins_In_30_Days] [nvarchar](max) NULL,
	[Risk_Client_Risk_Code] [nvarchar](50) NULL,
	[Amount_Purchased] [decimal](18, 2) NULL,
	[Amount_Deposited] [decimal](18, 2) NULL,
	[Instalment_Fee_Additional_Fees] [decimal](18, 2) NULL,
	[Amount_Financed] [decimal](18, 2) NULL,
	[Amount_Pts] [decimal](18, 2) NULL,
	[Amount_Received_Coll] [decimal](18, 2) NULL,
	[Amount_Received_On_Plan] [decimal](18, 2) NULL,
	[Since_Date] [datetime] NULL,
	[Property_Reference_Di_Proptype] [nvarchar](100) NULL,
	[Pooltype] [nvarchar](1000) NULL,
	[Nab_Dfn_Arrears] [decimal](18, 2) NULL,
	[Charge_Off_Date_1] [datetime] NULL,
	[Di_Chargeoffamt] [decimal](18, 2) NULL,
	[Original_Dfn_Arrears_Amount] [decimal](18, 2) NULL,
	[Nab_Updated_Balance] [decimal](18, 2) NULL,
	[Nab_Balance_Update_Date] [datetime] NULL,
	[Last_Cash_Advance_Date] [datetime] NULL,
	[Next_Payment_Due] [datetime] NULL,
	[Next_Payment_Amount] [decimal](18, 2) NULL,
	[Write_off_Date_1] [datetime] NULL,
	[Barcode_Data_Unique_Key] [nvarchar](1000) NULL,
	[Ocr_Line] [nvarchar](1000) NULL,
	[Age_Days] [nvarchar](1000) NULL,
	[Service_Count] [nvarchar](max) NULL,
	[On_Arrangement] [nvarchar](max) NULL,
	[Last_date_of_travel] [nvarchar](1000) NULL,
	[Bank_Branch] [nvarchar](max) NULL,
	[Experian_Def_Listing_Date] [datetime] NULL,
	[Experian_Listing_Amount] [decimal](18, 2) NULL,
	[Experian_Listing_Status] [nvarchar](max) NULL,
	[Veda_Def_Listing_Date] [datetime] NULL,
	[Veda_Listing_Amount] [decimal](18, 2) NULL,
	[Veda_Listing_Status] [nvarchar](max) NULL,
	[Dnb_Def_Listing_Date] [datetime] NULL,
	[Dnb_Listing_Amount] [decimal](18, 2) NULL,
	[Dnb_Listing_Status] [nvarchar](max) NULL,
	[Nab_Referral_Type] [nvarchar](max) NULL,
	[Di_Refund] [nvarchar](max) NULL,
	[Di_Refundbsb] [nvarchar](max) NULL,
	[Di_Refundaccno] [nvarchar](max) NULL,
	[Di_Refundaccname] [nvarchar](max) NULL,
	[Original_Debt_Amount] [decimal](18, 2) NULL,
	[Not_Yet_Due] [decimal](18, 2) NULL,
	[Current_Ptp_Status] [nvarchar](max) NULL,
	[Current_Ptp_Amount] [decimal](18, 2) NULL,
	[Current_Ptp_Date] [datetime] NULL,
	[Current_Ptp_Frequency] [nvarchar](max) NULL,
	[Last_Ptp_Date] [datetime] NULL,
	[Last_Ptpt_Freq] [nvarchar](max) NULL,
	[Last_Ptp_Amount] [decimal](18, 2) NULL,
	[Last_Ptp_Status] [nvarchar](max) NULL,
	[Future_Ptp_1_Amount] [decimal](18, 2) NULL,
	[Future_Ptp_2_Date] [datetime] NULL,
	[Future_PTP_2_Amount] [decimal](18, 2) NULL,
	[Future_Ptp_2_Date_1] [datetime] NULL,
	[Future_Ptp_3_Amount] [decimal](18, 2) NULL,
	[Future_Ptp_3_Date] [datetime] NULL,
	[Total_Paid] [decimal](18, 2) NULL,
	[Last_Rpc] [datetime] NULL,
	[Stat_Barred_Date] [datetime] NULL,
	[Dhs_Tenant] [nvarchar](max) NULL,
	[Account_Authorisation] [nvarchar](1000) NULL,
	[Required_Monthly_Payment_Amount_Last] [decimal](18, 2) NULL,
	[Required_Monthly_Payment_Amount_Next] [decimal](18, 2) NULL,
	[Di_Billsmooth] [nvarchar](max) NULL,
	[Di_Credit] [decimal](18, 2) NULL,
	[_90_Amount] [decimal](18, 2) NULL,
	[Service_Status] [nvarchar](max) NULL,
	[Disconnection_Date] [datetime] NULL,
	[Tpi_Name] [nvarchar](max) NULL,
	[Tpi_Reference_NAB_Internal_Reference_No] [nvarchar](max) NULL,
	[Arrange_Conf_By] [nvarchar](max) NULL,
	[Equifax_Flag] [nvarchar](max) NULL,
	[Optus_In_House_Merc_Date] [datetime] NULL,
	[Hardship_Start_Date] [datetime] NULL,
	[Hardship_End_Date] [datetime] NULL,
	[Payplan_Status_Receipt_Details] [nvarchar](max) NULL,
	[Person_3_Type_Code] [nvarchar](max) NULL,
	[Person_3_Id] [nvarchar](max) NULL,
	[Person_3_Customer_Id] [nvarchar](max) NULL,
	[Person_3_Surname] [nvarchar](max) NULL,
	[Cust1_Postal_Name_1] [nvarchar](max) NULL,
	[Person_3_First_Name] [nvarchar](max) NULL,
	[Cust1_Postal_Name_2] [nvarchar](max) NULL,
	[Person_3_Salutation] [nvarchar](max) NULL,
	[Person_3_Gender] [nvarchar](max) NULL,
	[Person_3_Date_Of_Birth] [datetime] NULL,
	[Cust2_Postal_Name1] [nvarchar](max) NULL,
	[Cust2_Postal_Name_2] [nvarchar](max) NULL,
	[Cust_1_Reference_Number] [nvarchar](max) NULL,
	[Cust_2_Reference_Number] [nvarchar](max) NULL,
	[Person_4_Type_Code] [nvarchar](max) NULL,
	[Person_4_Id] [nvarchar](max) NULL,
	[Person_4_Customer_Id] [nvarchar](max) NULL,
	[Person_4_Surname] [nvarchar](max) NULL,
	[Cust1_Res_Name_1] [nvarchar](max) NULL,
	[Person_4_First_Name] [nvarchar](max) NULL,
	[Cust1_Res_Name_2] [nvarchar](max) NULL,
	[Person_4_Salutation] [nvarchar](max) NULL,
	[Person_4_Gender] [nvarchar](max) NULL,
	[Person_4_Date_Of_Birth] [datetime] NULL,
	[Cust2_Res_Name_1] [nvarchar](max) NULL,
	[Cust2_Res_Name_2] [nvarchar](max) NULL,
	[Original_Account_Open_Date] [datetime] NULL,
	[Loan_Reschedule_Date] [datetime] NULL,
	[Primary_Customer_Start_Date] [datetime] NULL,
	[Employment_Status] [nvarchar](max) NULL,
	[Block_Release_Code] [nvarchar](max) NULL,
	[Block_Reclass_Date] [datetime] NULL,
	[Employment_Date] [datetime] NULL,
	[Preferred_Contact_Method] [nvarchar](1000) NULL,
	[Di_Payterms] [nvarchar](2000) NULL,
	[Di_Company] [nvarchar](2000) NULL,
	[Doc_Reference] [nvarchar](max) NULL,
	[Reason_for_Referral_Reason_For_Finalised_Account] [nvarchar](1000) NULL,
	[Vehicle_Make] [nvarchar](1000) NULL,
	[Id_Type] [nvarchar](1000) NULL,
	[Id_Number] [nvarchar](1000) NULL,
	[Expected_Recall_Date] [datetime] NULL,
	[Vehicle_Model_Last_Default] [nvarchar](1000) NULL,
	[Vehicle_Colour_Last_Default_Recall] [nvarchar](1000) NULL,
	[Vehicle_Year_Final_Exclusion] [nvarchar](1000) NULL,
	[Service_Phone] [nvarchar](max) NULL,
	[Default_Reported_Letter_Date] [datetime] NULL,
	[Default_Reported_Letter_Amount] [decimal](18, 2) NULL,
	[Referral_Type] [nvarchar](max) NULL,
	[Referral_Date_NPII_Date] [datetime] NULL,
	[Instalment_Frequency] [nvarchar](max) NULL,
	[Delinquent_Date] [datetime] NULL,
	[Number_Of_Arrangement_Payments] [nvarchar](max) NULL,
	[Arrangement_Review_Date] [datetime] NULL,
	[Premise_Id] [nvarchar](max) NULL,
	[Premise_Type] [nvarchar](max) NULL,
	[MIRN] [nvarchar](max) NULL,
	[Security_Discharge_Date] [datetime] NULL,
	[Other_Email_Addresses] [nvarchar](max) NULL,
	[Bill_To] [datetime] NULL,
	[Fee_Amount] [decimal](18, 2) NULL,
	[SP_RP_BUP] [nvarchar](max) NULL,
	[SP_RP_BUP_Number] [nvarchar](max) NULL,
	[Return_Mail_Flag] [nvarchar](max) NULL,
	[Recall_Days] [nvarchar](max) NULL,
	[Special_Case] [nvarchar](max) NULL,
	[Loan_Type] [nvarchar](max) NULL,
	[Loss_Reason_Motor_Loss_Category] [nvarchar](max) NULL,
	[Di_S88amt] [decimal](18, 2) NULL,
	[Account_Reference_Full_Account_Number] [nvarchar](max) NULL,
	[Plaint_No] [nvarchar](max) NULL,
	[Service_Fee] [decimal](18, 2) NULL,
	[Summons_Amount] [decimal](18, 2) NULL,
	[Kilometer_Fee] [decimal](18, 2) NULL,
	[Search_Fee] [decimal](18, 2) NULL,
	[Judg_Courts] [nvarchar](max) NULL,
	[Judgement_Amt_Sought] [decimal](18, 2) NULL,
	[Debits] [decimal](18, 2) NULL,
	[Offer_Percentage] [decimal](18, 2) NULL,
	[Credit_Date_Debtor] [datetime] NULL,
	[Nab_Hon_Host_Flag] [nvarchar](max) NULL,
	[Amt_Exceeded_Limit_Customer_Count] [decimal](18, 2) NULL,
	[Collection_Org] [nvarchar](max) NULL,
	[Secured_Flag] [nvarchar](max) NULL,
	[Primary_Default_Flag_Regulated_Flag] [nvarchar](max) NULL,
	[Insurance_Flag] [nvarchar](max) NULL,
	[Cust_Lending_Group_Num] [nvarchar](max) NULL,
	[Periodic_Payment_Frequency] [nvarchar](max) NULL,
	[Days_To_Last_Instal_Recmd_Security_Type] [nvarchar](max) NULL,
	[Last_Update_Date_Hardship_Reason] [nvarchar](max) NULL,
	[Last_Arrangement_Amount_Exited_Hardship] [decimal](18, 2) NULL,
	[Age_Band_Last_Arrangement_Period] [nvarchar](max) NULL,
	[Product_Code] [nvarchar](1000) NULL,
	[Product_Sub_Code] [nvarchar](1000) NULL,
	[Cust_1_2_3_4_Account_Count_Bpay_Biller_Code_Debt_Episode_Count] [nvarchar](max) NULL,
	[Cust_1_2_3_4_Account_Rel_Type_Aust_Post_Biller_Code_Customer_Bankrupt] [nvarchar](max) NULL,
	[Expected_Payment_Date] [datetime] NULL,
	[Credit_Code_Customer_Hardship] [nvarchar](max) NULL,
	[Customer_Sensitive_Pensioner] [nvarchar](max) NULL,
	[Arrears_Roll] [decimal](18, 2) NULL,
	[Case_List_Name] [nvarchar](max) NULL,
	[Recall_Date] [datetime] NULL,
	[Hardship_Duration_Appr] [nvarchar](max) NULL,
	[Hardship_Review_Date] [datetime] NULL,
	[Fee_Only_Credit_Card] [nvarchar](max) NULL,
	[Account_Active] [nvarchar](max) NULL,
	[Behaviour_Score] [nvarchar](max) NULL,
	[Behavior_Score_6_Mths_Ago] [nvarchar](max) NULL,
	[Debtor_1_Res_Addr_Status] [nvarchar](max) NULL,
	[Cust_Bpay_Biller_Code] [nvarchar](max) NULL,
	[Cycle_Day] [nvarchar](1000) NULL,
	[Eco_Flag] [nvarchar](1000) NULL,
	[DSS_Flag] [nvarchar](1000) NULL,
	[Cdl_Flag] [nvarchar](1000) NULL,
	[Cdl_Flag_Date_Added] [datetime] NULL,
	[Over_Limit] [decimal](18, 2) NULL,
	[Score_Colour_On_Load] [nvarchar](50) NULL,
	[Intel_Ptvul_Code] [nvarchar](max) NULL,
	[Last_Invoice_Date] [nvarchar](max) NULL,
	[Ledger_File_Type] [nvarchar](max) NULL,
	[Assignment_Value] [decimal](18, 2) NULL,
	[Original_Amount] [decimal](18, 2) NULL,
	[Closse_Date] [datetime] NULL,
	[Noa_Date] [datetime] NULL,
	[Noa_Amount] [decimal](18, 2) NULL,
	[Principle_Balance] [decimal](18, 2) NULL,
	[Bank_Account_Name] [nvarchar](max) NULL,
	[New_Postal_Address] [nvarchar](1000) NULL,
	[Blank1] [nvarchar](100) NULL,
	[Payment_Method] [nvarchar](100) NULL,
	[Settled_Date] [datetime] NULL,
	[Blank2] [nvarchar](100) NULL,
	[Contact_Details] [nvarchar](max) NULL,
	[Leak_Fixed] [nvarchar](max) NULL,
	[Leak_Issue] [nvarchar](max) NULL,
	[Solicitor_Contact] [nvarchar](max) NULL,
	[Date_Payment_Made] [datetime] NULL,
	[Receipt_No] [nvarchar](1000) NULL,
	[DI_Payment_Method] [nvarchar](100) NULL,
	[Customer_Contact_Details] [nvarchar](max) NULL,
	[Mail_Returned] [nvarchar](50) NULL,
	[Billing_Disput_Issue] [nvarchar](max) NULL,
	[Billling_Dispue_Details] [nvarchar](max) NULL,
	[Patient_Crn] [nvarchar](max) NULL,
	[Primary_Card_Holder_First_Name] [nvarchar](max) NULL,
	[Primary_Card_Holder_Surname] [nvarchar](max) NULL,
	[Primary_Card_Holder_Crn] [nvarchar](max) NULL,
	[Dva] [nvarchar](max) NULL,
	[Tac_Claim_No] [nvarchar](max) NULL,
	[Workcover_Claim_No] [nvarchar](max) NULL,
	[Voc_Claim_No] [nvarchar](max) NULL,
	[Ambulance_Member_No] [nvarchar](max) NULL,
	[Other_Claim_No] [nvarchar](max) NULL,
	[Once_Off_Documents_Sent_Arrears_Cure_Amount] [nvarchar](1000) NULL,
	[Once_Off_Doc_Date_Sent] [datetime] NULL,
	[Leak_Meter_Reading] [nvarchar](100) NULL,
	[Charges_Required_Details] [nvarchar](100) NULL,
	[Requested_Copy_Of_Account] [nvarchar](10) NULL,
	[Details_of_meter_reading] [nvarchar](100) NULL,
	[Disputed_Reading] [nvarchar](100) NULL,
	[Estimated_Reading] [nvarchar](100) NULL,
	[New_Postal_Addr1] [nvarchar](max) NULL,
	[New_Postal_Addr2] [nvarchar](200) NULL,
	[New_Postal_Addr3] [nvarchar](200) NULL,
	[New_Postal_Sub] [nvarchar](200) NULL,
	[New_Postal_State] [nvarchar](100) NULL,
	[New_Postal_Pcode] [nvarchar](50) NULL,
	[Solicitor_Address_1] [nvarchar](max) NULL,
	[Solicitor_Address_2] [nvarchar](max) NULL,
	[Solicitor_Address_3] [nvarchar](max) NULL,
	[Solicitor_Address_Sub] [nvarchar](200) NULL,
	[Solicitor_Address_State] [nvarchar](100) NULL,
	[Solicitor_Address_Pcode] [nvarchar](100) NULL,
	[Property_Address_Line_1] [nvarchar](max) NULL,
	[Property_Address_Line_2] [nvarchar](200) NULL,
	[Property_Address_Line_3] [nvarchar](200) NULL,
	[Property_Suburb] [nvarchar](200) NULL,
	[Property_State] [nvarchar](100) NULL,
	[Property_Post_Code] [nvarchar](50) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO


