/****** Object:  Table [dbo].[RC_DRINSURANCE]    Script Date: 22/05/2025 8:27:37 AM ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[RC_DRINSURANCE]') AND type in (N'U'))
DROP TABLE [dbo].[RC_DRINSURANCE]
GO

/****** Object:  Table [dbo].[RC_DRINSURANCE]    Script Date: 22/05/2025 8:27:37 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE dbo.RC_DRINSURANCE (
    FullDebtCode INT NOT NULL,
    ClientCode VARCHAR(20) NOT NULL,
    ClientGroup VARCHAR(50) NOT NULL,
    IncidentDate DATETIME NULL,
    IncidentPlace VARCHAR(1000) NULL,
    IncidentIntersectingStreet VARCHAR(1000) NULL,
    IncidentSuburb VARCHAR(100) NULL,
    IncidentState VARCHAR(10) NULL,
    IncidentPCode VARCHAR(10) NULL,
    IncidentMapRef VARCHAR(20) NULL,
    IncidentCode VARCHAR(20) NULL,
    LiabilityScore INT NULL,
    IncidentDescription VARCHAR(MAX) NULL,
    PortalNotes VARCHAR(MAX) NULL,
    RepName VARCHAR(100) NULL,
    RepRelationship VARCHAR(50) NULL,
    RepAddressLine1 VARCHAR(100) NULL,
    RepAddressLine2 VARCHAR(100) NULL,
    RepSuburb VARCHAR(50) NULL,
    RepState VARCHAR(10) NULL,
    RepPcode VARCHAR(10) NULL,
    RepBlockLetterYN VARCHAR(1) NULL,
    RepBlockSmsYN VARCHAR(1) NULL,
    RepBlockEmailYN VARCHAR(1) NULL,
    RepPhoneNo VARCHAR(1000) NULL,
    RepPhonetype VARCHAR(1000) NULL,
    RepPhoneScore VARCHAR(100) NULL,
    RepEmail VARCHAR(100) NULL,
    RepContactFirstYN VARCHAR(1) NULL,
    RepType VARCHAR(50) NULL,
    InsuredDriverName VARCHAR(100) NULL,
    InsuredDriverAddressLine1 VARCHAR(100) NULL,
    InsuredDriverAddressLine2 VARCHAR(100) NULL,
    InsuredDriverSuburb VARCHAR(50) NULL,
    InsuredDriverState VARCHAR(10) NULL,
    InsuredDriverPCode VARCHAR(10) NULL,
    InsuredDriverBlockLetterYN VARCHAR(1) NULL,
    InsuredDriverBlockSmsYN VARCHAR(1) NULL,
    InsuredDriverBlockEmailYN VARCHAR(1) NULL,
    InsuredDriverHomePhome VARCHAR(20) NULL,
    InsuredDriverWorkPhone VARCHAR(20) NULL,
    InsuredDriverLicenceNo VARCHAR(50) NULL,
    InsuredDriverEmail VARCHAR(100) NULL,
    InsuredPropertyType VARCHAR(50) NULL,
    InsuredPropertyPolicyNo VARCHAR(100) NULL,
    InsuredPropertyMake VARCHAR(100) NULL,
    InsuredPropertyModel VARCHAR(100) NULL,
    InsuredPropertyRegistration VARCHAR(50) NULL,
    InsuredPropertyAddress VARCHAR(200) NULL,
    InsuredPropertyDescription VARCHAR(3000) NULL,
    TotalPaidByInsurer DECIMAL(18,2) NULL,
    AmountReceived DECIMAL(18,2) NULL,
    RecoveryAmount DECIMAL(18,2) NULL,
    InitialRecoveryAmount DECIMAL(18,2) NULL,
    ClaimExcessWaivedYN VARCHAR(1) NULL,
    ClaimExcessPaidYN VARCHAR(1) NULL,
    ClaimExcessAmount DECIMAL(18,2) NULL,
    FinancialPendingRecovery DECIMAL(18,2) NULL,
    FinancialTotalIncurred DECIMAL(18,2) NULL,
    FinancialTotalRecoveries DECIMAL(18,2) NULL,
    FinancialRemainingReserves DECIMAL(18,2) NULL,
    FinancialTotalPaid DECIMAL(18,2) NULL,
    ExposureInformation VARCHAR(2000) NULL,
    ExposurePendingRec VARCHAR(2000) NULL,
    ExposureRemReserves VARCHAR(2000) NULL,
    ExposureTotalIncurred VARCHAR(2000) NULL,
    ExposureTotalPaid VARCHAR(2000) NULL,
    ExposureTotalRecoveries VARCHAR(2000) NULL,
    TPD_Name VARCHAR(100) NULL,
    TPD_AddressLine1 VARCHAR(100) NULL,
    TPD_AddressLine2 VARCHAR(100) NULL,
    TPD_Suburb VARCHAR(50) NULL,
    TPD_State VARCHAR(10) NULL,
    TPD_PCode VARCHAR(10) NULL,
    TPD_BlockLetterYN VARCHAR(1) NULL,
    TPD_BlockSmsYN VARCHAR(1) NULL,
    TPD_BlockEmailYN VARCHAR(1) NULL,
    TPD_LicenceNo VARCHAR(50) NULL,
    TPD_HomePhone VARCHAR(20) NULL,
    TPD_WorkPhone VARCHAR(20) NULL,
    TPD_Mobile VARCHAR(20) NULL,
    TPD_DateOfBirth DATETIME NULL,
    TPD_Email VARCHAR(100) NULL,
    TPO_Surname VARCHAR(50) NULL,
    TPO_Firstname VARCHAR(50) NULL,
    TPO_Title VARCHAR(20) NULL,
    TPO_Salutation VARCHAR(20) NULL,
    TPO_AddressLine1 VARCHAR(100) NULL,
    TPO_AddressLine2 VARCHAR(100) NULL,
    TPO_Suburb VARCHAR(50) NULL,
    TPO_State VARCHAR(10) NULL,
    TPO_PCode VARCHAR(10) NULL,
    TPO_BlockLetterYN VARCHAR(1) NULL,
    TPO_BlockSmsYN VARCHAR(1) NULL,
    TPO_BlockEmailYN VARCHAR(1) NULL,
    TPO_HomePhone VARCHAR(20) NULL,
    TPO_WorkPhone VARCHAR(20) NULL,
    TPO_Email VARCHAR(100) NULL,
    InsurerCode VARCHAR(20) NULL,
    InsurerNameOnDocument VARCHAR(100) NULL,
    InsurerTradingName VARCHAR(100) NULL,
    InsurerACN VARCHAR(20) NULL,
    InsurerNoClaimTPICode VARCHAR(20) NULL,
    InsurerClaimHandler VARCHAR(100) NULL,
    InsurerDX VARCHAR(50) NULL,
    InsurerContact VARCHAR(100) NULL,
    InsurerSalutation VARCHAR(20) NULL,
    InsurerPhoneNo VARCHAR(20) NULL,
    InsurerFaxNo VARCHAR(20) NULL,
    InsurerEmail VARCHAR(100) NULL,
    InsurerClaimNo VARCHAR(50) NULL,
    InsurerPolicyNo VARCHAR(50) NULL,
    TPP_Type VARCHAR(50) NULL,
    TPP_SelfInsuredYN VARCHAR(1) NULL,
    TPP_Quantum DECIMAL(18,2) NULL,
    TPP_Make VARCHAR(50) NULL,
    TPP_Model VARCHAR(50) NULL,
    TPP_Colour VARCHAR(30) NULL,
    TPP_YearOfManufacture INT NULL,
    TPP_Registration VARCHAR(20) NULL,
    TPP_TaxiRegistrationYN VARCHAR(1) NULL,
    TPP_Address VARCHAR(200) NULL,
    TPP_Description VARCHAR(2000) NULL,
    ShortDebtCode INT NULL
);